version: "2"

run:
  timeout: 10m
  tests: false

linters:
  default: none
  enable:
    - govet
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    paths:
      - "pkg/buf"
