// Copyright 2020-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package buffetch

import (
	"context"
	"fmt"
	"path/filepath"
	"testing"

	"buf.build/go/app"
	internal2 "github.com/inovacc/omni/pkg/buf/internal/buf/buffetch/internal"
	"github.com/inovacc/omni/pkg/buf/internal/bufpkg/bufparse"
	"github.com/inovacc/omni/pkg/buf/internal/pkg/git"
	"github.com/inovacc/omni/pkg/buf/internal/pkg/normalpath"
	"github.com/inovacc/omni/pkg/buf/internal/pkg/slogtestext"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TODO FUTURE: test ref from input config as well.
func TestGetParsedRefSuccess(t *testing.T) {
	t.Parallel()
	// This allows us to test an os-agnostic root directory
	root, err := filepath.Abs("/")
	require.NoError(t, err)

	// This lets us test an os-agnostic absolute path
	absPath, err := filepath.Abs("/foo/bar/..")
	require.NoError(t, err)
	expectedAbsDir, err := filepath.Abs("/foo")
	require.NoError(t, err)

	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedDirRef(
			formatDir,
			"path/to/some/dir",
		),
		"path/to/some/dir",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedDirRef(
			formatDir,
			".",
		),
		".",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedDirRef(
			formatDir,
			normalpath.Normalize(root),
		),
		root,
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedDirRef(
			formatDir,
			".",
		),
		"foo/..",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedDirRef(
			formatDir,
			"../foo",
		),
		"../foo",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedDirRef(
			formatDir,
			normalpath.Normalize(expectedAbsDir),
		),
		absPath,
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"path/to/file.tar",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeNone,
			0,
			"",
		),
		"path/to/file.tar",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"/path/to/file.tar",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeNone,
			0,
			"",
		),
		"file:///path/to/file.tar",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"path/to/file.tar",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeNone,
			1,
			"",
		),
		"path/to/file.tar#strip_components=1",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"path/to/file.tar.gz",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeGzip,
			0,
			"",
		),
		"path/to/file.tar.gz",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"path/to/file.tar.gz",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeGzip,
			1,
			"",
		),
		"path/to/file.tar.gz#strip_components=1",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"path/to/file.tgz",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeGzip,
			0,
			"",
		),
		"path/to/file.tgz",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"path/to/file.tgz",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeGzip,
			1,
			"",
		),
		"path/to/file.tgz#strip_components=1",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"path/to/file.tar",
			internal2.FileSchemeHTTP,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeNone,
			0,
			"",
		),
		"http://path/to/file.tar",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"path/to/file.tar",
			internal2.FileSchemeHTTPS,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeNone,
			0,
			"",
		),
		"https://path/to/file.tar",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatZip,
			"path/to/file.zip",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeZip,
			internal2.CompressionTypeNone,
			0,
			"",
		),
		"path/to/file.zip",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatZip,
			"/path/to/file.zip",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeZip,
			internal2.CompressionTypeNone,
			0,
			"",
		),
		"file:///path/to/file.zip",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatZip,
			"path/to/file.zip",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeZip,
			internal2.CompressionTypeNone,
			1,
			"",
		),
		"path/to/file.zip#strip_components=1",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"path/to/dir.git",
			internal2.GitSchemeLocal,
			nil,
			false,
			1,
			"",
			"",
		),
		"path/to/dir.git",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"path/to/dir.git",
			internal2.GitSchemeLocal,
			nil,
			false,
			40,
			"",
			"",
		),
		"path/to/dir.git#depth=40",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"path/to/dir.git",
			internal2.GitSchemeLocal,
			git.NewBranchName("main"),
			false,
			1,
			"",
			"",
		),
		"path/to/dir.git#branch=main",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"/path/to/dir.git",
			internal2.GitSchemeLocal,
			git.NewBranchName("main"),
			false,
			1,
			"",
			"",
		),
		"file:///path/to/dir.git#branch=main",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"path/to/dir.git",
			internal2.GitSchemeLocal,
			git.NewTagName("v1.0.0"),
			false,
			1,
			"",
			"",
		),
		"path/to/dir.git#tag=v1.0.0",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"hello.com/path/to/dir.git",
			internal2.GitSchemeHTTP,
			git.NewBranchName("main"),
			false,
			1,
			"",
			"",
		),
		"http://hello.com/path/to/dir.git#branch=main",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"hello.com/path/to/dir.git",
			internal2.GitSchemeHTTPS,
			git.NewBranchName("main"),
			false,
			1,
			"",
			"",
		),
		"https://hello.com/path/to/dir.git#branch=main",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"user@hello.com:path/to/dir.git",
			internal2.GitSchemeSSH,
			git.NewBranchName("main"),
			false,
			1,
			"",
			"",
		),
		"ssh://user@hello.com:path/to/dir.git#branch=main",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"user@hello.com:path/to/dir.git",
			internal2.GitSchemeSSH,
			git.NewRefName("refs/remotes/origin/HEAD"),
			false,
			50,
			"",
			"",
		),
		"ssh://user@hello.com:path/to/dir.git#ref=refs/remotes/origin/HEAD",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"user@hello.com:path/to/dir.git",
			internal2.GitSchemeSSH,
			git.NewRefNameWithBranch("refs/remotes/origin/HEAD", "main"),
			false,
			50,
			"",
			"",
		),
		"ssh://user@hello.com:path/to/dir.git#ref=refs/remotes/origin/HEAD,branch=main",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"user@hello.com:path/to/dir.git",
			internal2.GitSchemeSSH,
			git.NewRefName("refs/remotes/origin/HEAD"),
			false,
			10,
			"",
			"",
		),
		"ssh://user@hello.com:path/to/dir.git#ref=refs/remotes/origin/HEAD,depth=10",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"user@hello.com:path/to/dir.git",
			internal2.GitSchemeSSH,
			git.NewRefNameWithBranch("refs/remotes/origin/HEAD", "main"),
			false,
			10,
			"",
			"",
		),
		"ssh://user@hello.com:path/to/dir.git#ref=refs/remotes/origin/HEAD,branch=main,depth=10",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"path/to/dir.git",
			internal2.GitSchemeLocal,
			nil,
			false,
			1,
			"foo/bar",
			"",
		),
		"path/to/dir.git#subdir=foo/bar",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"path/to/dir.git",
			internal2.GitSchemeLocal,
			nil,
			false,
			1,
			"",
			"",
		),
		"path/to/dir.git#subdir=.",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"path/to/dir.git",
			internal2.GitSchemeLocal,
			nil,
			false,
			1,
			"",
			"",
		),
		"path/to/dir.git#subdir=foo/..",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"user@hello.com:path/to/dir.git",
			internal2.GitSchemeGit,
			git.NewBranchName("main"),
			false,
			1,
			"",
			"",
		),
		"git://user@hello.com:path/to/dir.git#branch=main",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"path/to/dir.git",
			internal2.GitSchemeGit,
			git.NewBranchName("main"),
			false,
			1,
			"",
			"",
		),
		"git://path/to/dir.git#branch=main",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"path/to/dir.git",
			internal2.GitSchemeGit,
			git.NewBranchName("main"),
			false,
			1,
			"subdir",
			"tree:0",
		),
		"git://path/to/dir.git#branch=main,filter=tree:0,subdir=subdir",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"path/to/file.bin",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeNone,
			nil,
		),
		"path/to/file.bin",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"path/to/file.bin.gz",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeGzip,
			nil,
		),
		"path/to/file.bin.gz",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"path/to/file.binpb",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeNone,
			nil,
		),
		"path/to/file.binpb",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"path/to/file.binpb.gz",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeGzip,
			nil,
		),
		"path/to/file.binpb.gz",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatJSON,
			"path/to/file.json",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeNone,
			nil,
		),
		"path/to/file.json",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatJSON,
			"path/to/file.json.gz",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeGzip,
			nil,
		),
		"path/to/file.json.gz",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatJSON,
			"path/to/file.json.gz",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeNone,
			nil,
		),
		"path/to/file.json.gz#compression=none",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatJSON,
			"path/to/file.json.gz",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeGzip,
			nil,
		),
		"path/to/file.json.gz#compression=gzip",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatTxtpb,
			"path/to/file.txtpb",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeNone,
			nil,
		),
		"path/to/file.txtpb",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatTxtpb,
			"path/to/file.txtpb.gz",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeGzip,
			nil,
		),
		"path/to/file.txtpb.gz",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatTxtpb,
			"path/to/file.txtpb.gz",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeNone,
			nil,
		),
		"path/to/file.txtpb.gz#compression=none",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatTxtpb,
			"path/to/file.txtpb.gz",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeGzip,
			nil,
		),
		"path/to/file.txtpb.gz#compression=gzip",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatYAML,
			"path/to/file.yaml",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeNone,
			nil,
		),
		"path/to/file.yaml",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatYAML,
			"path/to/file.yaml.gz",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeGzip,
			nil,
		),
		"path/to/file.yaml.gz",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatYAML,
			"path/to/file.yaml.gz",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeNone,
			nil,
		),
		"path/to/file.yaml.gz#compression=none",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatYAML,
			"path/to/file.yaml.gz",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeGzip,
			nil,
		),
		"path/to/file.yaml.gz#compression=gzip",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatYAML,
			"path/to/file.yaml",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeNone,
			map[string]string{
				"use_proto_names": "true",
			},
		),
		"path/to/file.yaml#use_proto_names=true",
	)
	testGetParsedRefError(
		t,
		internal2.NewOptionsInvalidKeysError("use_something_else"),
		"path/to/file.yaml#use_something_else=true",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatJSON,
			"path/to/file.json",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeNone,
			map[string]string{
				"use_proto_names": "true",
			},
		),
		"path/to/file.json#use_proto_names=true",
	)
	testGetParsedRefError(
		t,
		internal2.NewOptionsInvalidKeysError("use_something_else"),
		"path/to/file.json#use_something_else=true",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"",
			internal2.FileSchemeStdio,
			internal2.CompressionTypeNone,
			nil,
		),
		"-",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatJSON,
			"",
			internal2.FileSchemeStdio,
			internal2.CompressionTypeNone,
			nil,
		),
		"-#format=json",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatTxtpb,
			"",
			internal2.FileSchemeStdio,
			internal2.CompressionTypeNone,
			nil,
		),
		"-#format=txtpb",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatYAML,
			"",
			internal2.FileSchemeStdio,
			internal2.CompressionTypeNone,
			nil,
		),
		"-#format=yaml",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"",
			internal2.FileSchemeNull,
			internal2.CompressionTypeNone,
			nil,
		),
		app.DevNullFilePath,
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBin,
			"path/to/dir",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeNone,
			nil,
		),
		"path/to/dir#format=bin",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBin,
			"path/to/dir",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeNone,
			nil,
		),
		"path/to/dir#format=bin,compression=none",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBin,
			"path/to/dir",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeGzip,
			nil,
		),
		"path/to/dir#format=bin,compression=gzip",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"path/to/dir",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeNone,
			nil,
		),
		"path/to/dir#format=binpb",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"path/to/dir",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeNone,
			nil,
		),
		"path/to/dir#format=binpb,compression=none",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"path/to/dir",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeGzip,
			nil,
		),
		"path/to/dir#format=binpb,compression=gzip",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"/path/to/dir",
			internal2.GitSchemeLocal,
			git.NewBranchName("main"),
			false,
			1,
			"",
			"",
		),
		"/path/to/dir#branch=main,format=git",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"/path/to/dir",
			internal2.GitSchemeLocal,
			git.NewBranchName("main/foo"),
			false,
			1,
			"",
			"",
		),
		"/path/to/dir#format=git,branch=main/foo",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"path/to/dir",
			internal2.GitSchemeLocal,
			git.NewTagName("main/foo"),
			false,
			1,
			"",
			"",
		),
		"path/to/dir#tag=main/foo,format=git",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"path/to/dir",
			internal2.GitSchemeLocal,
			git.NewTagName("main/foo"),
			false,
			1,
			"",
			"",
		),
		"path/to/dir#format=git,tag=main/foo",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"path/to/dir",
			internal2.GitSchemeLocal,
			git.NewTagName("main/foo"),
			true,
			1,
			"",
			"",
		),
		"path/to/dir#format=git,tag=main/foo,recurse_submodules=true",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"path/to/dir",
			internal2.GitSchemeLocal,
			git.NewTagName("main/foo"),
			false,
			1,
			"",
			"",
		),
		"path/to/dir#format=git,tag=main/foo,recurse_submodules=false",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"path/to/dir",
			internal2.GitSchemeLocal,
			git.NewRefName("refs/remotes/origin/HEAD"),
			false,
			50,
			"",
			"",
		),
		"path/to/dir#format=git,ref=refs/remotes/origin/HEAD",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedGitRef(
			formatGit,
			"path/to/dir",
			internal2.GitSchemeLocal,
			git.NewRefName("refs/remotes/origin/HEAD"),
			false,
			10,
			"",
			"",
		),
		"path/to/dir#format=git,ref=refs/remotes/origin/HEAD,depth=10",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTargz,
			"path/to/file",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeGzip,
			1,
			"",
		),
		"path/to/file#format=targz,strip_components=1",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"path/to/file",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeNone,
			1,
			"",
		),
		"path/to/file#format=tar,strip_components=1",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"path/to/file",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeNone,
			1,
			"",
		),
		"path/to/file#format=tar,strip_components=1,compression=none",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"path/to/file",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeGzip,
			1,
			"",
		),
		"path/to/file#format=tar,strip_components=1,compression=gzip",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatZip,
			"path/to/file",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeZip,
			internal2.CompressionTypeNone,
			1,
			"",
		),
		"path/to/file#format=zip,strip_components=1",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"path/to/file.tar.zst",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeZstd,
			0,
			"",
		),
		"path/to/file.tar.zst",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"path/to/file.tar.zst",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeZstd,
			1,
			"",
		),
		"path/to/file.tar.zst#strip_components=1",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatZip,
			"path/to/file",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeZip,
			internal2.CompressionTypeNone,
			1,
			"",
		),
		"path/to/file#format=zip,strip_components=1",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"path/to/file.tar.zst",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeZstd,
			0,
			"foo/bar",
		),
		"path/to/file.tar.zst#subdir=foo/bar",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedArchiveRef(
			formatTar,
			"path/to/file",
			internal2.FileSchemeLocal,
			internal2.ArchiveTypeTar,
			internal2.CompressionTypeZstd,
			1,
			"foo/bar",
		),
		"path/to/file#format=tar,strip_components=1,compression=zstd,subdir=foo/bar",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBin,
			"path/to/file",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeZstd,
			nil,
		),
		"path/to/file#format=bin,compression=zstd",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"path/to/file.bin.zst",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeZstd,
			nil,
		),
		"path/to/file.bin.zst",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"path/to/file",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeZstd,
			nil,
		),
		"path/to/file#format=binpb,compression=zstd",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"path/to/file.binpb.zst",
			internal2.FileSchemeLocal,
			internal2.CompressionTypeZstd,
			nil,
		),
		"path/to/file.binpb.zst",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedModuleRef(
			formatMod,
			testNewModuleRef(
				t,
				"example.com",
				"foob",
				"bar",
				"v1",
			),
		),
		"example.com/foob/bar:v1",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedModuleRef(
			formatMod,
			testNewModuleRef(
				t,
				"example.com",
				"foob",
				"bar",
				"12345",
			),
		),
		"example.com/foob/bar:12345",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"github.com/path/to/file.bin",
			internal2.FileSchemeHTTPS,
			internal2.CompressionTypeNone,
			nil,
		),
		"https://github.com/path/to/file.bin",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBin,
			"github.com/path/to/file.ext",
			internal2.FileSchemeHTTPS,
			internal2.CompressionTypeNone,
			nil,
		),
		"https://github.com/path/to/file.ext#format=bin",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBin,
			"gitlab.com/api/v4/projects/foo/packages/generic/proto/0.0.1/proto.bin?private_token=bar",
			internal2.FileSchemeHTTPS,
			internal2.CompressionTypeNone,
			nil,
		),
		"https://gitlab.com/api/v4/projects/foo/packages/generic/proto/0.0.1/proto.bin?private_token=bar#format=bin",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"github.com/path/to/file.binpb",
			internal2.FileSchemeHTTPS,
			internal2.CompressionTypeNone,
			nil,
		),
		"https://github.com/path/to/file.binpb",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"github.com/path/to/file.ext",
			internal2.FileSchemeHTTPS,
			internal2.CompressionTypeNone,
			nil,
		),
		"https://github.com/path/to/file.ext#format=binpb",
	)
	testGetParsedRefSuccess(
		t,
		internal2.NewDirectParsedSingleRef(
			formatBinpb,
			"gitlab.com/api/v4/projects/foo/packages/generic/proto/0.0.1/proto.binpb?private_token=bar",
			internal2.FileSchemeHTTPS,
			internal2.CompressionTypeNone,
			nil,
		),
		"https://gitlab.com/api/v4/projects/foo/packages/generic/proto/0.0.1/proto.binpb?private_token=bar#format=binpb",
	)
	testGetParsedDirOrProtoFileRef(
		t,
		internal2.NewDirectParsedDirRef(
			formatDir,
			"foo",
		),
		nil,
		"foo",
	)
	testGetParsedDirOrProtoFileRef(
		t,
		internal2.NewDirectParsedDirRef(
			formatDir,
			"internal/testdata/direndsinproto.proto",
		),
		nil,
		"internal/testdata/direndsinproto.proto",
	)
	testGetParsedDirOrProtoFileRef(
		t,
		internal2.NewDirectParsedProtoFileRef(
			formatProtoFile,
			"foo.proto",
			internal2.FileSchemeLocal,
			false,
		),
		nil,
		"foo.proto",
	)
	testGetParsedDirOrProtoFileRef(
		t,
		internal2.NewDirectParsedDirRef(
			formatDir,
			"foo.proto",
		),
		nil,
		"foo.proto#format=dir",
	)
	testGetParsedDirOrProtoFileRef(
		t,
		internal2.NewDirectParsedProtoFileRef(
			formatProtoFile,
			"foo.proto",
			internal2.FileSchemeLocal,
			true,
		),
		nil,
		"foo.proto#include_package_files=true",
	)
	testGetParsedDirOrProtoFileRef(
		t,
		internal2.NewDirectParsedProtoFileRef(
			formatProtoFile,
			"",
			internal2.FileSchemeStdio,
			false,
		),
		nil,
		"-",
	)
	testGetParsedDirOrProtoFileRef(
		t,
		internal2.NewDirectParsedProtoFileRef(
			formatProtoFile,
			"",
			internal2.FileSchemeStdio,
			true,
		),
		nil,
		"-#include_package_files=true",
	)
}

func TestGetParsedRefError(t *testing.T) {
	t.Parallel()
	testGetParsedRefError(
		t,
		internal2.NewInvalidPathError(formatDir, "-"),
		"-#format=dir",
	)
	testGetParsedRefError(
		t,
		internal2.NewInvalidPathError(formatGit, "-"),
		"-#format=git,branch=main",
	)
	testGetParsedRefError(
		t,
		internal2.NewCannotSpecifyGitBranchAndCommitOrTagError(),
		"path/to/foo#format=git,branch=foo,tag=bar",
	)
	testGetParsedRefError(
		t,
		internal2.NewCannotSpecifyGitBranchAndCommitOrTagError(),
		"path/to/foo#format=git,branch=foo,tag=bar,ref=baz",
	)
	testGetParsedRefError(
		t,
		internal2.NewCannotSpecifyCommitOrTagWithRefError(),
		"path/to/foo#format=git,tag=foo,ref=bar",
	)
	testGetParsedRefError(
		t,
		internal2.NewDepthParseError("bar"),
		"path/to/foo#format=git,depth=bar",
	)
	testGetParsedRefError(
		t,
		internal2.NewDepthZeroError(),
		"path/to/foo#format=git,ref=foor,depth=0",
	)
	testGetParsedRefError(
		t,
		internal2.NewPathUnknownGzError("path/to/foo.gz"),
		"path/to/foo.gz",
	)
	testGetParsedRefError(
		t,
		internal2.NewPathUnknownGzError("path/to/foo.bar.gz"),
		"path/to/foo.bar.gz",
	)
	testGetParsedRefError(
		t,
		internal2.NewFormatOverrideNotAllowedForDevNullError(app.DevNullFilePath),
		fmt.Sprintf("%s#format=bin", app.DevNullFilePath),
	)
	testGetParsedRefError(
		t,
		internal2.NewFormatUnknownError("bar"),
		"path/to/foo#format=bar",
	)
	testGetParsedRefError(
		t,
		internal2.NewOptionsCouldNotParseStripComponentsError("foo"),
		"path/to/foo.tar.gz#strip_components=foo",
	)
	testGetParsedRefError(
		t,
		internal2.NewCompressionUnknownError("foo"),
		"path/to/foo.tar.gz#compression=foo",
	)
	testGetParsedRefError(
		t,
		internal2.NewOptionsInvalidKeysError("foo"),
		"path/to/foo.tar.gz#foo=bar",
	)
	testGetParsedRefError(
		t,
		internal2.NewOptionsInvalidForFormatError(formatTar, "path/to/foo.tar.gz#branch=main", "git options set"),
		"path/to/foo.tar.gz#branch=main",
	)
	testGetParsedRefError(
		t,
		internal2.NewOptionsInvalidForFormatError(formatDir, "path/to/some/foo#strip_components=1", "archive options set"),
		"path/to/some/foo#strip_components=1",
	)
	testGetParsedRefError(
		t,
		internal2.NewOptionsInvalidForFormatError(formatDir, "path/to/some/foo#compression=none", "compression set"),
		"path/to/some/foo#compression=none",
	)
	testGetParsedRefError(
		t,
		internal2.NewCannotSpecifyCompressionForZipError(),
		"path/to/foo.zip#compression=none",
	)
	testGetParsedRefError(
		t,
		internal2.NewCannotSpecifyCompressionForZipError(),
		"path/to/foo.zip#compression=gzip",
	)
	testGetParsedRefError(
		t,
		internal2.NewCannotSpecifyCompressionForZipError(),
		"path/to/foo#format=zip,compression=none",
	)
	testGetParsedRefError(
		t,
		internal2.NewCannotSpecifyCompressionForZipError(),
		"path/to/foo#format=zip,compression=gzip",
	)
	testGetParsedRefError(
		t,
		internal2.NewCannotSpecifyCompressionForZipError(),
		"path/to/foo#format=zip,compression=gzip",
	)
}

func testGetParsedRefSuccess(
	t *testing.T,
	expectedRef internal2.ParsedRef,
	value string,
) {
	testGetParsedRef(
		t,
		expectedRef,
		nil,
		value,
	)
}

func testGetParsedRefError(
	t *testing.T,
	expectedErr error,
	value string,
) {
	testGetParsedRef(
		t,
		nil,
		expectedErr,
		value,
	)
}

func testGetParsedRef(
	t *testing.T,
	expectedParsedRef internal2.ParsedRef,
	expectedErr error,
	value string,
) {
	parsedRef, err := newRefParser(slogtestext.NewLogger(t)).getParsedRef(
		context.Background(),
		value,
		allFormats,
	)
	if expectedErr != nil {
		if err == nil {
			assert.Equal(t, nil, parsedRef, "expected error")
		} else {
			assert.Equal(t, expectedErr, err)
		}
	} else {
		assert.NoError(t, err)
		if err == nil {
			assert.Equal(t, expectedParsedRef, parsedRef)
		}
	}
}

func testGetParsedDirOrProtoFileRef(
	t *testing.T,
	expectedParsedRef internal2.ParsedRef,
	expectedErr error,
	value string,
) {
	parsedRef, err := newDirOrProtoFileRefParser(slogtestext.NewLogger(t)).getParsedRef(
		context.Background(),
		value,
		dirOrProtoFileFormats,
	)
	if expectedErr != nil {
		if err == nil {
			assert.Equal(t, nil, parsedRef, "expected error")
		} else {
			assert.Equal(t, expectedErr, err)
		}
	} else {
		assert.NoError(t, err)
		if err == nil {
			assert.Equal(t, expectedParsedRef, parsedRef)
		}
	}
}

func testNewModuleRef(
	t *testing.T,
	registry string,
	owner string,
	name string,
	ref string,
) bufparse.Ref {
	moduleRef, err := bufparse.NewRef(registry, owner, name, ref)
	require.NoError(t, err)
	return moduleRef
}
