package nethttp

import (
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

// WriteNetscapeCookies writes cookies to a file in Netscape/Mozilla format.
// Format: domain\tflag\tpath\tsecure\texpiration\tname\tvalue
func WriteNetscapeCookies(path string, cookies []*http.Cookie) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("cookies: create dir: %w", err)
	}

	var b strings.Builder

	_, _ = fmt.Fprintln(&b, "# Netscape HTTP Cookie File")
	_, _ = fmt.Fprintln(&b, "# https://curl.haxx.se/rfc/cookie_spec.html")
	_, _ = fmt.Fprintln(&b, "# This file was generated by omni video auth.")
	_, _ = fmt.Fprintln(&b)

	for _, c := range cookies {
		domain := c.Domain
		flag := "TRUE"
		if !strings.HasPrefix(domain, ".") {
			flag = "FALSE"
		}

		path := c.Path
		if path == "" {
			path = "/"
		}

		secure := "FALSE"
		if c.Secure {
			secure = "TRUE"
		}

		var expires int64
		if !c.Expires.IsZero() {
			expires = c.Expires.Unix()
		}

		_, _ = fmt.Fprintf(&b, "%s\t%s\t%s\t%s\t%d\t%s\t%s\n",
			domain, flag, path, secure, expires, c.Name, c.Value)
	}

	return os.WriteFile(path, []byte(b.String()), 0o600)
}
